id: P1361EE23
initial_creation_type: input
source_metadata:
  title: Āryaśūra Series
  language: fr
  description: Texts by the great Indian master Āryaśūra, known to Tibetans as Lobpon
    Pawo (slob dpon dpa' bo), author of the famous Garland of Birth Stories (Jātakamālā)
  volume:
    0a43f53ac3844e388031e0978ed5b8da:
      title: Short Praise of the Buddha's Deeds
      parent: Praise
    33fcbc74633144d0b152e10beda26f7e:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
created_at: '2022-03-01T02:08:51.635061'
last_modified_at: '2022-03-01T02:08:51.635063'
